### ISSUE TITLE
SSO Login fails due wrong params order

### ISSUE THREAD

**Issue by waken22** [L1nkZ/rpatchur#21]
**Description**: The SSO Login on rpatchur makes the client crash, and it needs to be fixed and tested in newer clients to confirm if this still happens.
**Client Version**: 2015-09-16aRagexe
**What rpatchur does**: ``` "-1rag1" "-t:password" "username" ``` (results on a client crash)
**What rpatchur should do** ``` -t:password username server -1rag1``` (it works for me)
**Additional Info**: [Where i found the correct param order](https://rathena.org/board/topic/99701-guys-help-me-on-my-project-ultimate-launcher/?do=findComment&comment=276396)

And is important to know that the commas are sent to the emulator too. So it fails because the server receives "username" and tries to find an account including the commas, tested on a 2018 hercules emulator.

**Comment by L1nkZ** [comment]
Thanks for the report! I see @vstumpf has opened a PR so I'll review it and merge it.
