### ISSUE TITLE
Feature Request: Patching multiple grf in one patcher

### ISSUE THREAD

**Issue by hurtsky** [L1nkZ/rpatchur#24]
As like the title said, if possible to add a feature that we can patch multiple grf in one patcher,
so we might need multiple plist_url, and patch_url to identify each grf.

This just a suggestion, thank you for your hard work

**Comment by L1nkZ** [comment]
Hi @hurtsky,

I'm not sure I understand your request. THOR patches already allow patching multiple GRF by specifying the target GRF's name.
Or maybe you're asking about adding multiple patch server like in issue #18?

**Comment by hurtsky** [comment]
yes @L1nkZ , sorry delay responses. I will close this duplicate issue.  Thanks for your time
